EMS/Areas/Admin/Controllers/UserProfileController.cs
using EMS.BO;
using EMS.Model;
using EMS.Model.ViewModels;
using EMS.Repository;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EMS.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserProfileController : Controller
    {
        private ILeaveRepository _leaveRepository;
        private IAttendenceRepository _attendenceRepository;
        private IUserProfileRepository _userProfileRepository;

        public UserProfileController()
        {
            this._userProfileRepository = new UserProfileRepository(new EMSContext());
            this._attendenceRepository = new AttendenceRepository(new EMSContext());
            this._leaveRepository = new LeaveRepository(new EMSContext());
        }
        // GET: Admin/UserProfile
        public ActionResult Index()
        {
            var obj = this._userProfileRepository.GetAllEmployee();
            return View(obj);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(UserProfileVM userProfile)
        {
            if (ModelState.IsValid)
            {
                var user=this._userProfileRepository.IsUserExist(userProfile.EmployeeId, userProfile.EmailId);
                if(user is null)
                {
                    this._userProfileRepository.AddUserProfile(userProfile);
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Either EmailId or EmployeeId already exist.");
                }
                
            }
            return View(userProfile);
        }

        [HttpGet]
        public ActionResult ManageEmployee()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int SearchString)
        {
            UserProfileVM userProfile = this._userProfileRepository.GetEmployeeByEmpId(SearchString);
            if (userProfile == null)
            {
                TempData["searchempErrorMessage"] = $"No data found with the EmpId:{SearchString}";
            }
            ViewBag.UserProfile = userProfile;
            return View("ManageEmployee", userProfile);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManageEmployee(UserProfileVM userProfile)
        {
            if (ModelState.IsValid)
            {
                this._userProfileRepository.UpdateUserProfile(userProfile);
                return RedirectToAction("Index");
            }
            return View(userProfile);
        }


        [HttpGet]
        public ActionResult DeleteEmployee(int empId)
        {
            this._userProfileRepository.DeleteEmployee(empId);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult GetAttendence()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetAttendenceByEmpId(int EmpId, DateTime DateOfAttendence)
        {
            var attendence = this._attendenceRepository.GetEmployeeAttendence(EmpId, DateOfAttendence);
            if (attendence == null)
            {
                TempData["attErrorMessage"] = $"No data found with the EmpId:{EmpId} and Date:{DateOfAttendence}";
            }
            ViewBag.Attendence = attendence;
            return View("GetAttendence", attendence);
        }

        public ActionResult ActionOnLeave()
        {
            var obj = new List<SelectListItem>
        {
            new SelectListItem {Text="Pending", Value="Pending"},
            new SelectListItem {Text="Accepted", Value="Accepted"},
            new SelectListItem {Text="Rejected", Value="Rejected"},
        };
            ViewBag.status = obj;
            var leaves = this._leaveRepository.GetEmployeeLeaves();
            return View(leaves);
        }

        [HttpPost]
        public ActionResult StatusForLeave(int leaveId, string status)
        {
            this._leaveRepository.UpdateEmployeeLeaveStatus(leaveId,status);
            return Json("Success");
        }
    }
}

EMS/Controllers/UserProfileController.cs
using EMS.BO;
using EMS.CustomFilters;
using EMS.Model;
using EMS.Model.Utility;
using EMS.Model.ViewModels;
using EMS.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Web.Http;
using System.Web.Http.Cors;

namespace EMS.Controllers
{
    [JWTAuthorize]
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    [RoutePrefix("api/UserProfile")]
    public class UserProfileController : ApiController
    {
        private IUserProfileRepository _userProfileRepository;
        public UserProfileController()
        {
            this._userProfileRepository = new UserProfileRepository(new EMSContext());
        }

        [HttpGet]
        [Route("GetEmployeerByEmpId/{empId}")]
        public IHttpActionResult GetEmployeerByEmpId(int empId)
        {
            if (Helper.GetEmpIdFromClaims(User as ClaimsPrincipal) != empId)
                return Unauthorized();
            return Ok(this._userProfileRepository.GetEmployeeForAPI(empId));
        }

        [HttpPut]
        [Route("UpdateEmployee")]
        public IHttpActionResult UpdateEmployee(EmployeeRequestVM employeeRequestVM)
        {
            if (Helper.GetEmpIdFromClaims(User as ClaimsPrincipal) != employeeRequestVM.EmployeeId)
                return Unauthorized();
            this._userProfileRepository.UpdateEmployee(employeeRequestVM);
            //userProfileBO.UpdateEmployee(userProfile);
            return Ok(employeeRequestVM.EmployeeId);
        }

        //[HttpDelete]
        //[Route("DeleteEmployee")]
        //public IHttpActionResult DeleteEmployee(int empId)
        //{
        //    this._userProfileRepository.DeleteEmployee(empId);
        //    return Ok();
        //}

    }
}

EMS/Areas/Admin/Views/UserProfile/ActionOnLeave.cshtml
@model IEnumerable<EMS.Model.ViewModels.LeaveVM>
@{
    ViewBag.Title = "ActionOnLeave";
}

    <table class="table table-bordered table-responsive table-striped" style="margin-top:5rem;">
        <tr style="background-color:#3399CC;color:white">
            <th>
                EmployeeId
            </th>
            <th>
                No Of Days
            </th>
            <th>
                Reasons
            </th>

            <th>Status</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EmployeeId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoOfDays)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reason)
                </td>
                <td>
                    @Html.DropDownListFor(modelItem => item.Status, new SelectList(ViewBag.status, "Text", "Value", item.Status), new { @class = "form-control statusDrp", @id = item.PKLeaveId })
                </td>


            </tr>
        }

        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" class="text-center"> No Leave Available</td>
            </tr>
        }

    </table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $(".statusDrp").change(function () {
                var val = $(this).val();
                var LeaveId = $(this).attr("id");
                $.ajax({
                    type: "Post",
                    url: "/Admin/UserProfile/StatusForLeave",
                    data: { leaveId: LeaveId,status: val },
                    success: function (data) {
                        alert("Updated");
                        //window.location.reload();
                    }
                });
            });
        })

    </script>
}

EMS/Areas/Admin/Views/UserProfile/Create.cshtml
@model EMS.Model.ViewModels.UserProfileVM

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @type = "password", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            @*<div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>*@
            <div class="col-md-10">
                Male
                @Html.RadioButtonFor(model => model.Gender, "Male")
                Female
                @Html.RadioButtonFor(model => model.Gender, "Female")

                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.DateOfBirth, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Address,  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Workplace, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Workplace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Workplace, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <a class="btn btn-default" href="/Admin/Userprofile"> Cancel</a>
            </div>
        </div>
    </div>
}

EMS/Areas/Admin/Views/UserProfile/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

EMS/Areas/Admin/Views/UserProfile/GetAttendence.cshtml
@model EMS.Model.ViewModels.AttendenceVM
@{
    ViewBag.Title = "GetAttendence";
}

<style>
    .card {
        /* Add shadows to create the "card" effect */
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }

        /* On mouse-over, add a deeper shadow */
        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }
</style>

<div class="row" style="margin-top:5rem;">
    <div class="col-sm-offset-2 col-sm-8 ">
        @if (ViewBag.Attendence != null)
        {
            <form>
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Employee Id:</label>
                        <div class="col-md-9">
                            <input type="text" id="fname" name="EmpId" value="@Model.EmployeeId" class="form-control" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Date Of Attendence:</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.AttendenceOn, "{0:yyyy-MM-dd}", new { @readonly = "readonly", @type = "date", @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Working Hours:</label>
                        <div class="col-md-9">
                            <input type="text" id="fname" name="WorkingHours" value="@Model.WorkingHours" class="form-control" readonly>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-3 col-md-9">
                            <a href="/Admin/UserProfile/GetAttendence" class="btn btn-info">Go back to Search</a>
                        </div>
                    </div>
                </div>
            </form>
        }
        else
        {
            <div>
                <form action="/Admin/UserProfile/GetAttendenceByEmpId" method="Get">
                    <div class="form-horizontal">
                        @if (TempData["attErrorMessage"] != null)
                        {
                            <div class="alert alert-danger" role="alert">
                                @TempData["attErrorMessage"]
                            </div>
                        }
                        <div class="form-group">
                            <label class="col-md-3 control-label">Employee Id:</label>
                            <div class="col-md-9">
                                <input required type="number" id="fname" name="EmpId" value="" class="form-control ">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Date Of Attendence:</label>
                            <div class="col-md-9">
                                <input required type="date" name="DateOfAttendence" id="MeetingFromDate" value="" class="form-control " />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-md-9">
                                <input type="submit" class="btn btn-success" value="Search">
                            </div>
                        </div>

                    </div>
                </form>
            </div>
        }
    </div>
</div>

EMS/Areas/Admin/Views/UserProfile/Index.cshtml
@model IEnumerable<EMS.Model.ViewModels.UserProfileVM>
@using EMS.Model.Utility

@{
    ViewBag.Title = "Index";
}
<div class="row">
    <p class="m-0"> <h4 class="text-center" style="font-weight:600">Welcome @(User.Identity.Name)</h4></p>
</div>
<table class="table table-bordered table-responsive table-striped">
    <tr style="background-color:#3399CC;color:white;">
        <th>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Designation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Workplace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Designation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Workplace)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { SearchString = item.EmployeeId }) |
                @Html.ActionLink("Delete", "DeleteEmployee", new { empId = item.EmployeeId })
            </td>
        </tr>
    }

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="13" class="text-center"> No Employee Available</td>
        </tr>
    }

</table>

EMS/Areas/Admin/Views/UserProfile/ManageEmployee.cshtml
@model EMS.Model.ViewModels.UserProfileVM
@{
    ViewBag.Title = "ManageEmployee";
}

<style>
    .red{
        color:red;
    }
</style>

@if (ViewBag.UserProfile != null)
{
    using (Html.BeginForm("ManageEmployee", "UserProfile", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal" style="margin-top:5rem;">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.RoleId)

    <div class="form-group">
        @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.EmployeeId, "", new { @readonly = "readonly", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.EmailId, "", new { @readonly = "readonly", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        @*<div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>*@
        <div class="col-md-10">
            Male
            @Html.RadioButtonFor(model => model.Gender, "Male")
            Female
            @Html.RadioButtonFor(model => model.Gender, "Female")

            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.DateOfBirth, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Address,  new { @class = "form-control" } )
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Workplace, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Workplace, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Workplace, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
            <a href="/Admin/UserProfile/ManageEmployee" class="btn btn-info" style="margin-left:5px">Go to Search</a>
        </div>
    </div>
</div>
    }
}
else
{
    <div class="row" style="margin-top:5rem;">
        <div class="col-sm-offset-2 col-sm-10 col-md-10 col-xs-12">
            <div class="">
                <div class="col-sm-6 col-xs-12" style="padding-right:0px;">
                    @if (TempData["searchempErrorMessage"] != null)
                    {
                    <div class="alert alert-danger" role="alert">
                        @TempData["searchempErrorMessage"]
                    </div>
                    }
                    @using (Html.BeginForm("Edit", "UserProfile", FormMethod.Get, new { id = "frmClearSearch" }))
                    {
                        <div class="input-group" style="display:inline;margin-left:10px;">
                            <input class="form-control custFC" type="number" value="" id="SearchString"
                                   name="SearchString" placeholder="Enter EmployeeId">
                            <span class="input-group-append" style="margin-right:40px;">
                                <button type="submit" class="btn btn-default hidden-sm btndefaultColor" name="btnsrchterm" id="btnsrchterm" onclick="return validate()">
                                    <i class="fa fa-search">Search</i>
                                </button>
                            </span>

                        </div>
                        <p id="quizDescription"></p>
                    }
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    <script>
       
        function validate() {
            debugger;
            var searchString = $("#SearchString").val();
            if (searchString.length == 0) {
                $("#quizDescription").addClass("red").text("Please enter employee Id.");
                return false;
            } else {
                $("#quizDescription").text("");
                return true;
            }
        }
    </script>
}