EMS/Areas/Admin/Controllers/AuthenticateController.cs
using EMS.BO;
using EMS.Model;
using EMS.Model.PartialClass;
using EMS.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace EMS.Areas.Admin.Controllers
{
    public class AuthenticateController : Controller
    {
        //UserProfileBO userProfileBO = new UserProfileBO();

        private IUserProfileRepository _userProfileRepository;

        public AuthenticateController()
        {
            this._userProfileRepository = new UserProfileRepository(new EMSContext());
        }
        [HttpGet]
        // GET: Admin/Authenticate
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserModel userDetail)
        {
            if (ModelState.IsValid)
            {
                userDetail = this._userProfileRepository.Authenticate(userDetail);
                if (userDetail.IsValid)
                {
                    FormsAuthentication.SetAuthCookie(userDetail.EmailId, false);
                    return RedirectToAction("Index", "UserProfile");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "EmailId or password is incorrect");
                }
            }
            
            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

EMS/Areas/Admin/Views/Authenticate/Login.cshtml
@model EMS.Model.PartialClass.UserModel
@{
    ViewBag.Title = "Login";
}
<style>
    .card {
        /* Add shadows to create the "card" effect */
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }

        /* On mouse-over, add a deeper shadow */
        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }
</style>

<div class="row" style="margin-top:5rem;">
    <div class="col-sm-offset-4 col-sm-4 card">
        <h2 class="text-center">Login</h2>
        @using (Html.BeginForm("Login", "Authenticate", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @*@Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <label class="col-md-4 control-label">E-mail:</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(model => model.EmailId, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">Password:</label>
                    <div class="col-md-8">
                        @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Login" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>